import React from 'react';
import './Technical.css';
import CP from './CP.png';
import { Accordion, AccordionItem } from 'react-light-accordion';
import 'react-light-accordion/demo/css/index.css';
import Theory from './Theory.png';

class Technical extends React.Component {
    render() {
        return (
            <main className='body'>
                <h1>Technical</h1>
                <p>You are less likely to encounter the following types of arguments at traditional tournaments, but it’s still good to understand these concepts just in case it comes up in a particular round.  Most traditional judges really frown upon the use of plans, counterplans, NIBs, PICs, and Theory.  In my opinion, it’s a risky move to read any of those types of arguments in the very first speech unless you know for certain you have an ex-policy or circuit LD judge.  Otherwise, you really don’t want to accidently jump the gun and get rejected based on personal judge bias.</p>
                <p>What you want to do instead, is read those arguments in the rebuttal speech, and phrase it like your opponent has forced you into defending said argument.  It’s not your fault that you had to read these arguments, but rather your opponents for “forcing” you to.  But we’ll talk more about that later</p>
                <p>To be clear, NSDA does specify that there should not be plans read in LD debate.  But anyone who has debated for a while knows there are no actual rules  -you write your own during the round.</p>
                <h2>Plans</h2>
                <p>A plan is pretty straightforward.  It just means that you propose a “plan of action” that takes place.  It also means you will specify the specific implementation of that plan as well, providing information like the funding mechanism, actor, and specific details of the action.  Basically, you need to explain…</p>
                <Accordion>
                    <AccordionItem title='Who is the Actor in the Plan?'>
                        <p style={{padding : '1rem'}}>Is it the U.S. government, Supreme Court, or United Nations?  Specify what person or institution is responsible for carrying out the plan.</p>
                    </AccordionItem>
                    <AccordionItem title='What is the Funding Mechanism?'>
                        <p style={{padding : '1rem'}}>Who pays for the policy?  If carrying out your plan (like passing free healthcare policy) requires large amount of money you need to explain where that money is going to come from.</p>
                    </AccordionItem>
                    <AccordionItem title="What is the Plan Text?">
                        <p style={{padding : '1rem'}}>What exactly do you want to do or make happen?  How will it happen?  This is usually where you need a “solvency advocate” as well.  Someone with credentials who supports the plan so the audience knows it’s not something you pulled out of nowhere.”</p>
                        <p style={{padding : '1rem'}}><strong>Example: </strong>“According to Alan from the Wall Street Journal, The U.S.F.G. should pass a revenue neutral carbon tax policy”<br/>The actor in this plan is the U.S.F.G., the funding mechanism is not needed since the policy is “revenue neutral,” the solvency advocate is “Alan from the WSJ,” and the plan itself is to “pass a carbon tax policy.”</p>
                    </AccordionItem>
                </Accordion>
                <p></p>
                <p>Now, let’s look at some examples and see why someone would want to read a plan in the first place.</p>
                <Accordion>
                    <AccordionItem title='Example: Topic  -”The United States Ought to Promote Democracy in the Middle East”'>
                        <p style={{padding : '1rem'}}>If you do your topic research you realize a few things.  First, is that there have been tons of ways in which the U.S. has attempted to promote democracy in the Middle East.  These have included assassination of rebel leaders, stationing of the Fifth Fleet, and bribery of current political leaders.  But then you notice that all of these actions have lead to pretty bad consequences.  Assassinations lead to new, more violent leaders being propped up, the Fifth Fleet oppresses natives, and bribery keeps the peace but also corrupt leaders in power.</p>
                        <p style={{padding : '1rem'}}>So what do you do?  To avoid criticisms on ALL the past democracy promotion methods, you, as the aff, propose a PLAN that doesn’t make the same mistakes.  This plan will looks something like “The U.S. will promote democracy in the Middle East through funding the Middle Eastern Partnership Initiative (MEPI).  MEPI does not use military rule to establish control, but rather works to build coalitions by integrating cultural differences.”</p>
                        <p style={{padding : '1rem'}}>The resolution is very broad and as a result there are many different aspects the neg can attack.  By specifying the exact type of democracy to promote, the aff is able to shrink the scope of the debate and make it harder for the neg to rebut.  Now, the neg doesn’t just have to prove the democracy promotion in general is bad, but that the MEPI itself is a bad policy.  If the neg were to talk about different cases where U.S. democracy promotion failed, you could just effectively ignore them and say, “yeah, those were bad policies for sure.  That’s why we are ONLY going to use MEPI now.  It avoids all the drawbacks of our past efforts.”</p>
                        <p style={{padding : '1rem'}}><strong>Takeaway: </strong>By specifying a very specific type of action you will undertake as “part” of the entire resolution, you can effectively zone out many negative arguments and limit the scope of the debate to just this particular plan (which you will ideally know very comprehensively).</p>
                    </AccordionItem>
                    <AccordionItem title='Example: Topic -”Countries Should Prohibit the Production of Nuclear Power”'>
                        <p style={{padding : '1rem'}}>Given this topic, an obvious neg strat is to talk about the dangers of having nuclear power plants that could potentially malfunction or terrorists could attack.  Therefore, an obvious aff strat is to specify building a specific type of nuclear power plant that avoids these issues. This will look something like, “Countries should invest in Molten Salt Nuclear Reactors (MSRs).  These reactors use up existing stockpiles of nuclear waste and convert them into stable forms of power making these materials unavailable for use in nuclear weapons.”</p>
                        <p style={{padding : '1rem'}}>See how by specifying one type of nuclear reactor we can access way more advantages while also avoiding the disadvantages of nuclear reactors in general?  What we saying essentially is that “Yes, nuclear power in general is dangerous.  We should prohibit them all EXCEPT for one type of reactor, MSRs, since they allow us to clean up all of our existing nuclear waste.”  There was also evidence at the time that proved MSRs could not be repurposed into nuclear weapons by terrorist groups so that was also a big bonus.</p>
                        <p style={{padding : '1rem'}}><strong>Takeaway: </strong>As the aff, it is always in your best interest to limit the scope of what the neg can attack.  In this case, we limit the neg from being able to attack “all nuclear power,” to only being able to attack “Molten Salt Reactors.”</p>
                    </AccordionItem>
                </Accordion>
                <h3>Recontextualize for Traditional Debate</h3>
                <p>But remember there’s a catch!  Traditional judges don’t like plans and will probably vote against you just for bringing one up.  To avoid this, don’t read the plan in your constructive.  Read it as a response in the rebuttal speech, and frame it as “your opponent is forcing you to read a plan by reading this argument.”  This strategy is also most time efficient and optimal because you can pick and choose which plan to read depending on what the opponent’s case position is.  It leads to you being able to pick the best plan for the situation (the one that lets you wiggle out of the most neg arguments), and also doesn’t make you look like a rule breaker (you had no choice).</p>
                <p><strong>Tip: </strong>If you use this strategy, the neg also doesn’t have a CX left, so they won’t be able to clarify your plan if they’re confused.</p>
                <p><strong>Example: </strong>Topic -”The U.S. Ought to Pass a Universal Basic Income”</p>
                <p>NEG: “Contention 1: A UBI would devastate the U.S. economy by increasing tax rates by 40%”</p>
                <p>AFF (you): “My opponent’s first contention claims that a UBI would devastate the U.S. economy.  My response is that a UBI doesn’t actually lead to any increase in taxes, thus his claim is false and the impacts don’t happen.  According to [insert author], a UBI should actually be paid for by redistributing current entitlement spending and phasing out welfare.”</p>
                <p>See how you just read a plan-text “the USFG will pass a UBI by redistributing entitlement spending and phasing out welfare,” as a response to Contention 1 on the neg?  This is good -it can function as both a rebuttal and a plan, and if the opponent calls you out in CX for reading a plan, you can just say you were forced to by their own first contention.  Opponent shouldn’t have tried to specify your funding-mechanism so you provided your own.  Totally fine and no judge will fault you for that.</p>
                <h2>Counterplans (CPs)</h2>
                <p>A counter plan is like the plan but for the neg.  It is when the neg offers an alternative course of action that is different from the one implied by the resolution.  The goal of the neg will then be to prove that the counterplan is more ideal than the implied plan of the resolution.</p>
                <p><strong>Example: </strong>Topic -”The U.S. Ought to Ban Handguns”</p>
                <p>A counterplan to this topic would the neg saying “Instead of banning handguns, the U.S. should just enforce stricter background check regulations.”  See how we’re saying “instead of doing the resolution, we should do this counter-plan that’s better?”  That’s what a counter-plan is -forcing the aff to not only prove that the resolution is good, but also that your counterplan is bad.</p>
                <p>There are a few components to constructing a counterplan type argument as well...</p>
                <Accordion>
                    <AccordionItem title='Text'>
                        <p style={{padding : '1rem'}}>The text is just explaining what your counterplan is.  Instead of doing the resolution, what will we be doing instead that’s better?  In the handgun example above, the text would be the statement “Instead of banning handguns, the U.S. should just enforce stricter background check regulations.”</p>
                    </AccordionItem>
                    <AccordionItem title='Solvency'>
                        <p style={{padding : '1rem'}}>The solvency section is where you show that doing the counterplan will solve all the same problems that the aff is trying to solve.  This part is important because you are basically saying that doing the aff plan is unnecessary if we just do the counterplan.  Well, to prove that, you need to show that everything the aff is trying to fix could be fixed just as well using your counterplan.  In the handgun example above, the background checks counterplan would prove solvency by reading evidence that stricter background checks would decrease gun violence in the same way a handgun ban would.</p>
                    </AccordionItem>
                    <AccordionItem title='Net Benefit'>
                        <p style={{padding : '1rem'}}>Remember how in the solvency section, you proved that doing your counterplan would solve the same problems as doing the aff plan?  That’s not enough.  If the counterplan and aff plan both solve the same issues which one is better?<br/><br/>To convince people that doing the counterplan is better than doing the aff plan, you need net benefits on the counterplan, or reasons why the counterplan brings about even more benefits than the aff plan.  In the above handgun example, the net benefit would be something like “not only do background checks stop gun violence, they also avoid the development of black markets because people will still have legal means of obtaining a means of defense.”  So here, the reason why doing the counterplan (background checks) is net better than doing the aff plan (ban guns), is because the counterplan avoids black markets whereas the aff plan creates them.</p>
                    </AccordionItem>
                </Accordion>
                <h3>Counterplan Competitiveness</h3>
                <p>The key to a counterplan working that most debaters neglect is competitiveness.  A good way to think about it is in terms of opportunity cost and “either-or” scenarios.  You can either do the aff plan or the counterplan: not both.  It’s important for a counterplan to be “in competition” with the aff plan, because if it is possible to do both the counterplan and the aff plan, then there’s no longer a reason to reject the aff plan: we would just do both.  And absent a direct reason to negate, one usually affirms.</p>
                <Accordion>
                    <AccordionItem title='Permutation'>
                        <p style={{padding : '1rem'}}>A permutation is a highly efficient response the aff makes against non-competitive counterplans.  If the counterplan is not competitive, the affirmative can permutate the counterplan, which basically means that they say “we will do both the counterplan and the aff plan.”  The judge will then continue to affirm because if you can implement both the aff plan and counterplan -there’s no direct reason to negate the aff plan (the aff plan hasn’t been proven bad yet).”</p>
                        <p style={{padding : '1rem'}}><strong>Example: </strong>if the counterplan to “ban handguns” is to “ban ammunition instead,” the aff would just say “perm do both -we can ban handguns and ban ammunition.”  See how in doing so, the aff has just stolen all the neg ground and made all the benefits of the counterplan their own?  This is because banning ammunition, although it is a plan, doesn’t compete with the aff plan of banning handguns.</p>
                    </AccordionItem>
                </Accordion>
                <p>So how does a counterplan become competitive?  There are two ways.</p>
                <Accordion>
                    <AccordionItem title='Mutual Exclusivity'>
                        <p style={{padding : '1rem'}}>A counterplan is by definition mutually exclusive if it is impossible to do both the aff plan and counterplan at the same time.  To prove that your counterplan is mutually exclusive, you can use the idea of opportunity cost.  This means that if you do the aff plan, there will not be enough resources left to do the counterplan: the aff plan would thus be an opportunity cost to doing the counterplan (which is better).</p>
                        <p style={{padding : '1rem'}}><strong>Example: </strong>On the 2018 State LD topic, the aff had to defend a universal basic income for all citizens.  A common neg counterplan was the Earned Income Tax Credit (EITC) CP which basically said that instead of giving a flat amount of cash to every citizen, we should give more money to the people who are in poverty but also have jobs (the net benefit being that it would incentivize more people to find work instead of being lazy).  To summarize since I’m sure a few of you won’t know what either of those are, imagine the EITC CP gives a lot of money to poor people with job, and UBI gives money to all the poor people regardless.  Do you see how the UBI is an opportunity cost to EITC?  If you’re already giving money to everyone it defeats the whole purpose of EITC.  And you can’t have both EITC and UBI because they each cost trillions (it’s already hard enough just to implement one). </p>
                        <p style={{padding : '1rem'}}>Another way to prove mutual exclusivity is just when the aff plan physically cannot take place in the world of the counterplan.  This one’s pretty straightforward.  If the aff wants to ban all handguns and you read a background checks CP, it’s pretty obvious that you can’t ban all the handguns and have background checks (because there would be no one to check…).</p>
                    </AccordionItem>
                    <AccordionItem title='Net Benefits'>
                        <p style={{padding : '1rem'}}>You can also make a counterplan competitive by proving that doing the counterplan itself is net better than doing the counterplan and the aff plan together.  This means that the world in which only the counterplan takes place is a better world (on the net) than the world where both the counterplan and aff plan happen.  This seems counterintuitive right?  If both the CP and aff plan are good why would doing both be worse than just doing the CP?  It can happen.  Just off the top of the head think about how a progressive tax and flat tax might both have their benefits independently, but in a world where they are combined, people would get way overtaxed and starve.</p>
                        <p style={{padding : '1rem'}}><strong>Example: </strong>In the 2017 State LD topic, the aff had to support a policy to create a Right to Housing.  A common neg strat I encountered was neg reading a counterplan that said “creating a right to housing would take too long and polarize congress, so the government should just pass normal housing policies instead.”  If you didn’t catch it, basically neg said that creating a new “right” would lead to unnecessary conflict as opposed to just creating better housing policies to reduce homelessness.  So you wouldn’t be able to perm this CP as the aff because a world in which there is a right to housing AND better housing laws is WORSE than just a world with better housing laws because BOTH worlds solve homelessness, BUT the world where you pass it as a “right” leads to government conflict making it net worse.</p>
                    </AccordionItem>
                </Accordion>
                <p></p>
                <p>Okay now that you know all the individual components of a CP, let’s take a look at an example.</p>
                <p><strong>Example: </strong>Topic -The U.S.F.G. Ought To Ban All Handguns</p>
                <img src={CP} width='50%' height='50%' alt='CP'/>
                <p></p>
                <p>As you can see in the above image, the CP text is to “Let people keep buying handguns but only after receiving a purchasing license.”  The solvency advocate is Guo15 who references Connecticut as an empirical example.  The solvency evidence is provided by Rudolph et al 15 who indicates a 40% reduction in homicides if we follow the purchasing license approach.  The CP is mutually exclusive with with aff plan because you cannot ban all handguns and require people to get purchasing licenses.  The net benefit is that purchasing licenses won’t lead to the creation of black markets and normal people who want guns for self defense can still purchase.</p>
                <h3>Recontextualize for Traditional Debate</h3>
                <p>So now you know how to create a killer counterplan, but this doesn’t solve the occasional problem of having a traditional judge who doesn’t appreciate the use of these arguments.  What do you do then?</p>
                <Accordion>
                    <AccordionItem title='Method 1'>
                        <p style={{padding : '1rem'}}>The first method is to read your CP, but don’t let it function as a CP.  You need to read it as a disadvantage (DA) instead and phrase it as an opportunity cost argument.  So don’t word it like “instead of doing the aff do this CP” rather word it like “the aff is BAD because we CAN’T do the CP anymore.”  This is a pretty clever way to sneak in a CP as a DA and in my experience, traditional judges are totally cool with it.  Applied to the handgun scenario, we would say, “We shouldn’t ban handguns outright because it robs policymakers of the opportunity to pass purchasing license laws which are proven to decrease homicides.”</p>
                    </AccordionItem>
                    <AccordionItem title='Method2'>
                        <p style={{padding : '1rem'}}>The second, much better, method is to state that the CP is going to happen by itself anyways, solve the problems, and thus make the aff plan pointless.  You are not advocating a CP, you are making an accurate analytical prediction of what the future will look like.  This method of course, relies on you having a good card and solvency advocate who provides solid reasons why the CP is going to happen.  Applied to the handgun scenario, we would say, “Many states like Connecticut have already adopted stricter background checks and purchasing license laws and more will follow.  It is proven that these policies are much more effective at combating gun violence yet the affs handgun ban would get in the way of these reforms and prevent us from saving lives.”</p>
                    </AccordionItem>
                </Accordion>
                <h2>Necessary but Insufficient Burdens (NIBs)</h2>
                <p></p>
                <img src='http://static.squarespace.com/static/5005e162c4aa44899228d266/50b6f2e0e4b03c06ac4f97dd/50b6f535e4b03c06ac4faf5b/1354167680389/'/>
                <p>Necessary but Insufficient Burdens are exactly what they sound like.  It refers to when you set up a burden structure for the opponent and force them to prove something before the round can even be evaluated.  Therefore, it is necessary for them to prove this point, but insufficient for this point to win them the round.  Basically, it’s setting up your opponent for a lose lose situation (they either fail to prove and lose or successfully prove and nothing happens).  You can see how this type of argument could be potentially abusive and frowned upon.</p>
                <p>NIB’s usually sound like this: “before you can evaluate the opposition's case, they must first prove X because [insert reason].”  Usually, the only time I will read a NIB is to force the opponent to defend a plausible plan of action.  This, coupled with a pragmatism framework, isn’t abusive at all in my opinion -it’s good to pigeon hold your opponent to reality so they don’t start going down the road of vague abstraction.</p>
                <p>Here’s an example of a more abusive one.</p>
                <Accordion>
                    <AccordionItem title='Topic -The U.S.F.G. ought to guarantee reparations for African Americans'>
                        <p style={{padding : '1rem'}}>There are a few NIBs you can read on this resolution.  First, you can claim that the aff has to prove that there even exists a form of reparation that can make amends for slavery, otherwise it wouldn’t count as a real reparation.  Second, you can claim that the Aff has to prove that every African American wants reparations since the resolution implies you are giving it to everyone.  Third, you can claim that the Aff has to prove the reparations would actually occur and pass through congress since it is unlikely given the current triple red government.<br/><br/>Notice how all the above burdens we give the aff have nothing to do with the round itself.  None of those burdens will prove whether reparations as a moral concept are good or bad, so we basically are forcing the Aff to prove a bunch of statements before they can even access the round.</p>
                    </AccordionItem>
                </Accordion>
                <h3>Contextualize to Traditional Debate</h3>
                <p>The NIB I like to read on the Neg is forcing the Aff to prove plausibility.  The key is, don’t read the argument like a spike.  Have your entire case position support the NIB and it’ll be a lot less sketchy for the judge to vote on.  This means you should read a pragmatism framework that says debaters need to actually prove material impacts and weigh them.  I also like to include the analytic that governments cannot be obligated to do the impossible -that would make them immoral agents if they failed.  Therefore the government can only be morally obligated to do what is actually possible.  With these two arguments on the board, you would have a legitimate claim to force the aff to prove that his plan would actually occur.</p>
                <Accordion>
                    <AccordionItem title='Example: Topic -The U.S.F.G. Ought to Guarantee a Right to Housing'>
                        <p style={{padding : '1rem'}}>As the neg I would say, “None of my opponents impacts actually happen because a right to housing policy would never pass through a triple red government.  Furthermore, even if it did, there aren’t enough vacant houses in the right locations nor a federal budget to ensure that every homeless person gets a home.  Until my opponent is able to prove a way for the government to obtain funding, and a strategy that could actually ensure every homeless person in America gets a home, you should negate because the aff doesn’t actually lead to any of its impacts in the real world which is the most important factor for pragmatic policymaking.”</p>
                    </AccordionItem>
                </Accordion>
                <h2>Plan Inclusive Counterplans (PICs)</h2>
                <p>A plan inclusive counterplan (PIC) is a type of argument read by the neg that says “do the aff plan except for a small exception.”  So you can see how this could be pretty abusive because you don’t really have to engage the aff plan on a very deep level.  All you need to do is find a small part of the plan that could be changed to make it better.  For example, if the aff says “We should pass a carbon tax in the U.S.” a PIC to this would be neg saying “Pass the carbon tax everywhere except this really small city where people are poor and need carbon to power their homes.”</p>
                <p>When neg reads a PIC, they steal all the Aff ground because the neg’s position becomes do the aff plan but with a minor tweak that makes it even better.  None of the advantages in the aff plan matter anymore because they also happen in the neg world.</p>
                <Accordion>
                    <AccordionItem title='Example: Topic -U.S.F.G Ought to Guarantee a Universal Basic Income'>
                        <p style={{padding : '1rem'}}>For context, a UBI is a cash payment to every single person in the country regardless of wealth.  Therefore, the neg could read a PIC that says “we should give a UBI to everyone except Bill Gates.”  Now see how the aff goes from having to prove that a UBI in general is good, to specifically having to prove why Bill Gates needs a UBI.”</p>
                    </AccordionItem>
                </Accordion>
                <h3>Dealing With PICs on the Aff</h3>
                <p>So PICs are definitely annoying to deal with if you’re on the aff.  This is another reason why I advise against ever reading a plan in the 1AC (remember how we save it for the rebuttals).  If you don’t read an aff plan in the 1AC your opponent cannot read a PIC.  And if they’re stupid enough to read one anyways, you can just say that the PIC was the aff plan all along.  That’s why you keep your aff vague at the beginning so the neg can’t pin you down with PICs and CPs.</p>
                <p>Take the UBI example.  If the neg says we should give a UBI to everyone except Bill Gates, you can claim that was the aff’s plan all along.  That the aff was never going to give a UBI to Bill Gates.  Now you need to argue the definition of “universal” and defend whether you need to give a UBI to everyone for it count -but at least you haven’t shot yourself in the foot already in the 1AC and still have the option to contest this.</p>
                <h3>Recontextualize for Traditional Debate</h3>
                <p>Again, traditional judges aren’t usually cool with PICs and if we’re being honest they are a tad unfair.  So if you’re going to read a PIC anyways you need to word it a little differently.  Instead of a call to action (do the aff except for this), you want to word it as a truth/falsity paradigm.  That is, you say that for the aff to prove the resolution “true” they need to prove their plan (or implied plan) is good in all instances -including the exception you bring up.  You can also think of it as reading the PIC as a DA as well.  You are basically saying the aff plan is bad because it could be done better with an exception.</p>
                <Accordion>
                    <AccordionItem title='Example: Topic -U.S.F.G. Ought to Guarantee a Universal Basic Income'>
                        <p style={{padding : '1rem'}}>Instead of reading the PIC as “instead of giving everyone a UBI we should give it to everyone besides Bill Gates,” you should say, “Giving a UBI to wealthy individuals like Bill Gates trades off with actual helping those most in need -the bottom 20%.”  See how in the above example, there is an implied PIC (it is implied that we should give a UBI only to the poor people and not the rich), but it is worded as an opportunity cost DA?  So you’ve basically created an opportunity cost argument that can only be answered by treating it like a PIC!</p>
                    </AccordionItem>
                    <AccordionItem title='Example: Topic -U.S.F.G. Ought to Guarantee a Right to Housing'>
                        <p style={{padding : '1rem'}}>So the PIC I read on this topic was that instead of providing a right to housing for everyone who is homeless, we should only provide housing to those who are “chronically” homeless (i.e. people who aren’t just temporarily out of a job and have proven disabilities that make it impossible for them to find work).  But I didn’t word it like a PIC.  I read the argument as, “Giving a right to housing to people who are only temporarily homeless is not only impossible but trades off with actually providing targeted housing support for those who are chronically homeless.”  Again, I word the PIC as an opportunity cost so it functions as a DA but can only be taken out if treated like a PIC.</p>
                    </AccordionItem>
                </Accordion>
                <h2>Conditionality</h2>
                <p>Conditionality is a concept that defines the status of plans and counterplans.  A plan or counterplan can either have a status of “condition’ or ‘unconditional.’  Take for a example a CP that the neg reads.  If the Aff is able to explain why the CP is net worse, does the neg have to continue defending the CP or can he just kick the argument and pretend it never happened?  If the CP is conditional it means you can kick the argument whenever you want, and if it’s unconditional you cannot kick the argument whenever you want and must continue defending it as part of your case position.</p>
                <p>In general, it is seen as more fair for plans and counterplans to have a status of unconditionality.  It’s also probably better for debate because the debater reading the plan or counterplan would actually have to engage the arguments against it rather than just kicking out of it and going for a different argument.  Conditional plans/CPs create a shifting advocacy model of debate where anytime you try to engage a plan/CP the opponent just shifts to a different one without actually engaging your responses.</p>
                <Accordion>
                    <AccordionItem title='Example: Topic -The U.S.F.G. Ought to Ban all Handguns'>
                        <p style={{padding : '1rem'}}>If the Neg reads a CP that says the U.S.F.G. should just enforce laws that force people to receive a purchasing license before acquiring firearms, and the Aff proves that the purchasing license CP would actually lead to racial discrimination regarding who is able to receive a license, neg can do two things.  Neg can either kick the CP and focus attacks on why a handgun ban is bad, or defend the CP and try to prove that there wouldn’t be discrimination in purchasing license policies. </p>
                        <p style={{padding : '1rem'}}><strong>Analysis: </strong>See how if the Neg just kicks the CP, the aff just wasted a bunch of time reading TURNs on the CP for nothing?  If the CP is conditional it creates a “no win” scenario for the Aff -either they don’t TURN to the CP in which case the CP wins and steals all the Aff ground OR they do TURN the CP but then it just gets kicked and the aff doesn’t win anything.</p>
                    </AccordionItem>
                </Accordion>
                <h3>Contextualize for Traditional Debate</h3>
                <p>So obviously conditional plans and counterplans are super strategic.  They force the opponent to fight on two fronts with no risk to you because even if the opponent wins offense on your plan/CP you can kick it.</p>
                <Accordion>
                    <AccordionItem title='Using Conditional Arguments'>
                        <p style={{padding : '1rem'}}>If you describe your argument in CX as a risk free win-win type, it looks blatantly unfair.  What you want to do is ground conditionality in the principle of policymaking in general.  If your opponent calls you out for being able to kick out of plans, just explain that policymakers do the exact same thing everyday.  If problems arise with a bill that a congressman supports, it is perfectly reasonable for him to scrap it, make changes, and propose a better one.  You need to set forth the idea that the debate is an ever evolving discussion about the resolution, and we will probably go through multiple iterations of an ‘ideal’ plan of action, zealously critiquing each along the way, until the end of the debate where the best plan will become clear.  This of course means your opponent can read conditional arguments too.  And why shouldn’t they!  If you are able to read conditional arguments so should the opposition.  If you word it this way, in my experiences, the judges are okay with it because both debaters have the same strategic opportunity. </p>
                    </AccordionItem>
                    <AccordionItem title='Responding to Conditional Arguments'>
                        <p style={{padding : '1rem'}}>The buzzword you need to use when combatting conditional arguments is “shifting advocacy.”  A shifting advocacy is universally understood by traditional judges as being unfair and un-substantive.</p>
                        <p style={{padding : '1rem'}}>The first thing you need to do is pin down the opponent in CX, where you ask them “if I win offense against your CP/Plan are you allowed to kick it?  If they say yes, then in your rebuttal speech you point out that the opponent’s case is a shifting advocacy because no matter how good your attack is against the opposing case, they can always “shift out of it” with no consequences.  This usually makes it very clear to the judge that abuse is occuring.  But you have to point it out this way.  My coach has judged hundreds of debate rounds and I can’t tell you how many times he has told me that he wanted to vote down a debater who had a shifting advocacy but the other debater was just bad at explaining why it was shifty.</p>
                    </AccordionItem>
                    <AccordionItem title='Special Case'>
                        <p style={{padding : '1rem'}}>One of the most annoying things for the neg debater is when the aff reads multiple conditional plans.  If you respond to each plan, the aff is just going to kick all of them in the next speech except the one you were least prepared against and go for it.  This is usually hard to pin down in CX if your up against a good debater because they will say something along the lines of “I’m allowed to propose multiple different ways to achieve the goal -they’re all equally viable and covered by the resolution.”</p>
                        <p style={{padding : '1rem'}}>What you want to do in this situation as the neg is to ask this question: “Why is it my burden as the neg to prove that every iteration of the aff is wrong, and not your burden as the aff to prove that there is one iteration that is good?”  That usually seals the deal.  You basically make the argument that the burden of the aff is to prove that one policy works and that it’s not the neg to prove that every possible aff plan under the topic is bad.  This is pretty intuitive right -because there are millions of possible aff plans there’s no way it’s your job as the neg to prove that every single one doesn’t work.  It should rather be the aff job to do research and find one that’s the best -then we debate that plan.</p>
                    </AccordionItem>
                </Accordion>
                <p></p>
                <h1>Theory</h1>
                <p >I want to first preface this section by saying that it is extremely rare that you will actually ever read Theory in a traditional debate.  It should also never be your goal to read Theory in a traditional debate because once theory gets introduced the round becomes a total toss up (as traditional judges more often use judge intervention than not).  If you’re confident you are the better debater don’t leave it up to chance -beat them on the flow and avoid having to read a theory shell.</p>
                <p>With that said, I have occasionally had to read Theory in traditional debates before -both in PF and LD.  The issues have ranged from little things like PIC bad theory to straight up ethics violations.  The important thing was first confirming with the judges prior to the round beginning that they were capable AND willing to evaluate theory arguments. </p>
                <p>A theory shell refers to the writing of an additional rule in the debate round that both debaters will comply under.  Here is the common structure for a theory shell:</p>
                <Accordion>
                    <AccordionItem title='A: Interpretation'>
                        <p style={{padding : '1rem'}}>The interpretation is the rule you are setting forth in the debate round.  It basically tells us what we should and shouldn’t be able to do during the debate.  Keep in mind that the interpretation needs to literally tell the debaters what can and can’t be done -it’s not enough to just say “doing X is bad” you need to explicitly state “neither debater may do X.”</p>
                        <p style={{padding : '1rem'}}><strong>Example: </strong>“A is the interpretation.  Debaters may not read read conditional counterplans that do the aff plan except for a few exceptions.  To clarify, debaters may not read conditional PICs.”</p>
                        <p style={{padding : '1rem'}}>In the above example, our interpretation states clearly that neither debater should be allowed to read conditional PICs.  Conditional simply means that the neg can choose to kick the PIC if the aff manages to TURN it (so it’s clearly even more abusive there is no win strat for the aff on this argument).</p>
                    </AccordionItem>
                    <AccordionItem title='B: Violation'>
                        <p style={{padding : '1rem'}}>The violation section is where you explain how the opponent has violated the interpretation.  It’s pretty self-explanatory -tell the judge what the opponent did that broke the rules.  To prove a violation you can either refer to something the opponent said in their previous speech or refer to a statement they made in CX.</p>
                        <p style={{padding : '1rem'}}><strong>Example: </strong>“B is the violation.  The neg clearly violates -according to their advocacy they would do the aff plan except for this small exception and also conceded in CX that the status of the CP was conditional.”</p>
                    </AccordionItem>
                    <AccordionItem title='C: Standards'>
                        <p style={{padding : '1rem'}}>The standards section is where you provide reasons why your interpretation is good for debate and should be followed.  Standards function as individual arguments under your interpretation and can sort of be thought of as a cross between a warrant/contention.  They allow you to generate offense off your shell.  The standards section has three components: tag, warrant, and internal link.  </p>
                        <p style={{padding : '0rem 1rem 1rem 1rem'}}>The tag is usually just one or two words long and explain the premise of the argument your standard makes.  Common tags are ground (the opposing argument unfairly steals my ground), reciprocity (the opposing argument sets up unfair burdens of each debater), predictability (the opposing argument is unfairly unpredictable -there’s no way to prepare for it), and academic integrity (the opposing strategy violates norms of academic integrity).  The tag basically just helps the judge organize the flow and prefaces what you are about to say.</p>
                        <p style={{padding : '0rem 1rem 1rem 1rem'}}>The warrant explains what happens or what has already happened as a result of your interpretation not being followed and also why it’s bad (kind of).  This is where you describe how and why the opposition is being unfair.</p>
                        <p style={{padding : '0rem 1rem 1rem 1rem'}}><strong>Example: </strong>“C is the standard.  First is ground.  PICs moot 6 minutes of the 1AC offense by doing almost all the aff.  The only way the aff can recover time and have a shot at winning is by spending all of the 1AR turning the CP.  Condo removes this final strategy of combating PICs because you can just kick the CP and defend the squo if my TURNs beat you, thus destroying the possibility of combatting the time skew and destroying fairness.”</p>
                        <p style={{padding : '0rem 1rem 1rem 1rem'}}>See how in the above example, we have the tag (ground) and warrant (everything else) which explains why the opponent is being crazy abusive.  The final component of the standard is the internal link and it just serves to create a link between your warrant and the voter.  You’ve made your point about why condo PICs are unfair, but now you need to link that to the voter and explain why it’s important to be fair in the first place!</p>
                    </AccordionItem>
                    <AccordionItem title='D: Voter'>
                        <p style={{padding : '1rem'}}>The voter is the final component of the syllogistic shell.  You’ve made a rule, explained how your opponent violated it, and why it is unfair.  Now you need you need to tell the judge why they should care about the theory argument.  This is usually done by outlining the duties inherent to debate judges (i.e. it is their duty as a judge to promote a fair debate environment).  The most common voters are fairness and education. </p>
                        <p style={{padding : '1rem'}}><strong>Example: </strong>“D is the voter.  Fairness is a voter because debate is a competitive activity and it is the job of the judge to evaluate who did the better debating but that’s impossible unless there’s a fair playing field upon which to make the evaluation.”</p>
                    </AccordionItem>
                </Accordion>
                <p></p>
                <p>Put together and the theory shell will look like this:</p>
                <img src={Theory} alt='THeory' height='70%' width='70%' border='2' />
                <h3>Paradigm Issues</h3>
                <p>Even though the theory shell itself is complete there are still a few strategic gaps in the argument.  For example, what should happen if you win the theory argument (do you drop the debater or just the argument in question), and how should the judge evaluate your theory shell (reasonableness vs. competing interps).  These are all referred to as the judge’s paradigm issues.</p>
                <p>There are three paradigmatic issues that need to be addressed in the round:</p>
                <Accordion>
                    <AccordionItem title='Drop the Argument vs. Drop the Debater'>
                        <p style={{padding : '1rem'}}>What happens when you win a theory debate?  Does the argument you read theory against get dropped or does the debater you are reading theory against lose?  This paradigmatic issue basically tells the judge whether to evaluate theory first before substance or apply theory to the substance of the debate.  For example, if the argument is drop the debater the judge will vote for who wins the round solely off who wins the theory argument.  If it’s is drop the argument, depending on who wins the theory shell, the judge will or will not drop the argument first, then evaluate the substance of the round.</p>
                        <p style={{padding : '1rem'}}>The debater reading the shell will usually want drop the debater since it is a huge time commitment to read a shell and also serves the goal of deterring abusive arguments in the first place.  Also this paradigmatic issue should be proportional to the abuse.  If the opposing debater only read a marginally abusive argument drop the argument should be sufficient.</p>
                    </AccordionItem>
                    <AccordionItem title='The Reverse Voting Issue (RVI)'>
                        <p style={{padding : '1rem'}}>The reverse voting issue (RVI) answers the question of who wins the round if the opposing debater wins the theory argument.  If you read a theory shell but the opposing debater wins the theory debate, do you lose the round?  If theory is an RVI, then yes you would lose the debate.</p>
                        <p style={{padding : '1rem'}}>As you can see, a common critique against RVIs is that it creates a chilling effect where debaters become scared to read theory against in round abuse for fear that the other debater, being more skilled, will win the RVI and thus win the round too.  But an argument for RVIs is that it creates a burden structure for the person reading the shell so that they can win on both fronts yet the opposing debater must answer theory and win substance in order to win the round.</p>
                    </AccordionItem>
                    <AccordionItem title='Competing Interpretations vs Reasonability'>
                        <p style={{padding : '1rem'}}>Competing interpretations, as the name implies, is a lot stricter.  It asks the judge to evaluate the round based on who has the better interpretation or counter interpretation.  Under this paradigm, even if the debater answering theory reads a counter interp, as long as the interpretation is marginally better than the counter interpretation, the debater who read theory wins and vice versa.  Basically competing interpretations asks the judge to find the “best” rule for debate, and the debater it belongs to wins the theory argument.</p>
                        <p style={{padding : '1rem'}}>Reasonability, on the other hand, only asks the judge to determine if the debater answering theory was reasonably fair or educational.  Every argument can arguably be “abusive” so this paradigm purports that as long as the abuse is not egregious, the judge should let it fly.  Of course this may be a little subjective (it’s basically left up to the judge’s intuition whether the debater was being too abuse), but the debater answering theory can also bring up reasonability brightlines to make it clearer to the judge what constitutes “reasonability.”</p>
                        <p style={{padding : '1rem'}}>Reasonability Brightlines define the threshold of what is abusive or not.  For example, if the aff reads a condo PICs bad theory shell, the neg can say they are reasonable because 1) the PIC was disclosed on the wiki for a month 2) the PIC is grounded in topic literature and almost every academic author references it in their papers.</p>
                    </AccordionItem>
                </Accordion>
                <h3>Responding to Theory</h3>
                <p>There are multiple ways to respond to theory.  You can create a counter interpretation which is the same thing as an interpretation but which justifies your side, you can TURN the interp standards, or attack the voters.  But if I went in depth on how to do all that, this piece would be twice as long.  And since we are specializing here in traditional debate, there is really only one way you should respond to theory argument levied against you.</p>
                <p>First, never read abusive arguments.  Even though you’re reading arguments similar to conditional plans/CPs, PICs, and NIBs, you are wording them in a way so that they only function as DA remember.  Your opponent can’t read theory against DAs -that’s what we call frivolous theory and traditional judges hate frivolous theory and see it as a form of whining.  Therefore, you will respond to most theory arguments with an “I meet,” which means you meet the other debater’s interpretation and there’s no violation.  If the interpretation is you can’t read condo PICs, no problem you’re just reading an opportunity cost DA, and if the interpretation is you can’t read NIBs no problem your just reading a pragmatism framework that says it would be better if actions were plausible.</p>
                <h3>Contextualize for Traditional Debate</h3>
                <p>Okay this is going to sound kind of weird because we just went over how to write a theory shell, but, never ever read an entire theory shell with traditional judges.  Doing so is extremely time inefficient because when it comes to theory, traditional judges always either intervene or they don’t -they won’t look at the voter or paradigm issues (most of the time they won’t even flow the shell).  All you have to do is point out the abuse and why it’s abusive -you don’t need an explicit interpretation, voter, or paradigm issues.  Point out where the opponent is being abusive and the judge will either intervene or they won’t.  Any additional components you provide are wasted explaining something the judge already knows or is perfectly willing to apply for you.  The last thing you want to do though is go all in on theory, the judge doesn’t intervene, and you lose the substance debate. </p>
                <p>So how do you read “theory” efficiently in a traditional debate.  You call it an independent voter and give a few sentences max.  The first sentence explains what the opponent did.  The second sentence explains why it’s abusive.  That’s it.  After that it’s up to the judge to either intervene or not.</p>
                <Accordion>
                    <AccordionItem title='Normal Case'>
                        <p style={{padding : '1rem'}}><strong>Example:</strong>“First, I would like to point out that my opponent is reading a conditional PIC because his entire advocacy is that we do the entirety of the aff except for this small exception and furthermore in CX stated that it would be perfectly fine for him to kick this argument if I was able to generate offense off it.  Not only are PICs extremely abusive since they steal all the affs ground without fully engaging the substance of the arguments, by making it conditional, my opponent has created a shifting advocacy making it impossible for me to engage his case because any argument I attack will just be shifted away.  I believe this to be an unethical and extremely unfair practice which ruins debate making it an independent voter.”</p>
                        <p style={{padding : '1rem'}}>In the above example we give the judge all the information they need without setting up all the structures of a theory shell.  This is all you need to do with traditional judges.  The above is a very convincing argument -you will still be able to effectively engage substance and 9 times out of 10 a traditional judge will vote off this independent voter.  </p>
                    </AccordionItem>
                    <AccordionItem title='Special Case: Evidence Violations'>
                        <p style={{padding : '1rem'}}>Almost every time I’ve read theory in traditional debate has been because of one issue.  When a debater paraphrases his evidence and doesn’t actually read the card, it allows them to misconstrue what the author is actually saying which gives them an edge in the round.  I’ve had to read theory against these debaters multiple times (with 100% success) at both prelims and elims at State and a few national circuit PF tournaments.  </p>
                        <p style={{padding : '1rem'}}>First, in CX ask for some evidence, confirm that none of the cards are cut and they’re just reading their own written summaries.  Then, in the rebuttal speech, tell the judge how the opponent has paraphrased all his evidence and show one piece of evidence where he paraphrased extremely badly (lied) and basically say, “Look, for all we know he could be lying about all his evidence and we would never know because he isn’t using the author's exact words like you’re supposed to.”  I think the best way to frame the issue is that the debater has “deviated from debate practices mean to maintain academic integrity to gain an edge” and that such behavior is extremely suspicious.  </p>
                        <p style={{padding : '1rem'}}>Honestly, it’s hard to win this argument with lay judges since they don’t know what “cutting cards” means.  That’s why you don’t want to overcommit on the theory argument -just a few sentences to point out the abuse will do.  If you look at my round 6 at the 2017 CA State LD tournament, all three of my judges were lay/traditional and none of them bought the theory argument, but I was able to use it as a time suck so that while the opponent was busy overcommitting on theory thinking I was going to go for it, I went and won the substance debate.</p>
                        <p style={{padding : '1rem'}}><strong>Takeaway: </strong>Read theory against debaters who paraphrase and don’t cut cards -even if the judge doesn’t buy it’s a good time suck that doesn’t take much time to read and you can kick it in the last speech and go for substance.</p>
                    </AccordionItem>
                </Accordion>
                <p></p>
            </main>
        )
    }
}
export default Technical;