import React from 'react';
import './Rebuttals.css';
import A2 from './A2.png';
import { Accordion, AccordionItem } from 'react-light-accordion';
import 'react-light-accordion/demo/css/index.css';


class Rebuttals extends React.Component {
    render() {
        return (
            <main className='body'>
                <h1>Rebuttals</h1>
                <p>In general you should go into rounds with a good idea of all the potential rebuttals you might face or use.  The hallmark of a great debater is being able to confidently defend their case when under attack and easily deconstructing their opponent’s cases through critical thinking and logical reasoning.</p>
                <h2>Preparing Frontlines</h2>
                <p>But thinking on your feet for every argument is tiring and unsustainable.  It's smart to have prepared responses to common arguments written down so that you can focus more time for the hardest arguments.</p>
                <img src={A2} heigh='70%' width='70%' alt='frontlines' border='2'/>
                <p>In the above example, we are reading a poll to prove a majority support for our plan.  However, anticipating that the opponent might attack the idea of "following the majority" by saying that it could lead to atrocities like slavery, we come up with solid answers beforehand.  Notice how the arguments are strategically layered on top of each other.  We'll touch up more on this strategy later.</p>
                <h2>Defensive Rebuttals</h2>
                <p>Defensive rebuttals are, as the name implies, “defensive.”  Winning a defensive rebuttal casts doubt on your targeted contention, but doesn’t provide a reason why that contention is necessarily bad or leads to bad consequences.  Although defensive rebuttals can mitigate the impact or link of a contention, it ultimately won’t win you the round and at best sets the argument chain to net neutral.  Think of it as “damage control.”  There’s inevitably going to be some damage control but you don’t want your entire rebuttal speech to be just that.</p>
                <p>There are two main types of defensive rebuttals:</p>
                <Accordion>
                    <AccordionItem title='No Warrant'>
                        <p style={{padding : '1rem'}}>This is basically when you say your opponent’s argument is untrue or their evidence/justification is either missing or false.  These include evidence indicts and when your opponent just says something blatantly wrong.</p>
                        <p style={{padding : '1rem'}}><strong>Example: </strong>“My opponent’s first contention claims that increased gun sales lead to more crime, but doesn’t bring up a single piece of evidence that proves that.”</p>   
                        <p style={{padding : '1rem'}}>As we stated, defensive arguments won’t win you the round, but they can be very efficiently leveraged.  Pointing out that your opponent doesn’t have specific evidence to prove a link takes 5 seconds.  To make it even more powerful, rephrase it like this: “UNTIL my opponent provides specific evidence proving this claim, disregard his entire contention.”  Now the burden is on your opponent to provide new evidence in his next speech, and even that will only give him a net neutral position at best after wasting precious time.</p>
                    </AccordionItem>
                    <AccordionItem title='Non Unique'>
                        <p style={{padding : '1rem'}}>This is basically when you say that your opponent’s argument isn’t unique to his position, meaning that the impact will occur in both worlds.  If the impact occurs in both the aff and neg worlds, then the argument becomes a moot point since it isn’t a reason to prefer one world over the other.</p>
                        <p style={{padding : '1rem'}}><strong>Example: </strong>“My opponent’s third contention claims that passing a carbon tax will lead to the companies shifting away from carbon emissions.  This argument is non unique as studies already indicate carbon will become economically infeasible so companies will transition anyways.”</p>
                        <p style={{padding : '1rem'}}>Non-unique arguments aren’t very efficient.  It doesn’t take a lot of time to respond to, and implicitly concedes the link to the impact.  At best it is a net neutral for you so it’s not a smart use of time.  In my experience non-unique arguments should be saved for the final speech where you sneak them into your weighing analysis or comparative worlds paradigm.  That’s the only way they can be used efficiently.</p>
                    </AccordionItem>
                </Accordion>
                <h2>Offensive Rebuttals</h2>  
                <p>Offensive rebuttals are, as the name implies, “offensive” in nature.  This means that they generate offense off of your opponent’s arguments.  It’s like saying “not only is my opponent wrong, he’s so wrong that it’s helping my case.”</p>
                <p>There are two main types of offensive rebuttals:</p>
                <Accordion>
                    <AccordionItem title='link TURN'>
                        <p style={{padding : '1rem'}}>A link TURN takes your opponent’s contention, and says instead of their claim leading to these good consequences it actually instead leads to these bad consequences.  If you opponent’s claim is that X leads to Y, you are saying no actually X leads to Z and Z is very bad.</p>
                        <p style={{padding : '1rem'}}><strong>Example: </strong>“My opponent’s second contention is that gun control will lead to fewer shootings because it depletes the number of guns in circulation.  TURN this argument against him, because gun control would actually lead to the creation of black markets, causing a massive illegal boom in the gun industry.”</p>
                        <p style={{padding : '1rem'}}>Link TURNS are extremely efficient.  They don’t take a lot of time to read if you’re careful, and are a net positive towards your case.  Now, your opponent can no longer leave the rebuttal be, they must defend against your rebuttal as if it was a new argument (which it is) because it offense against their position.  Always try to maximize the number of link TURNS you read.  I used to keep an entire file of general link TURNS to common arguments, and whenever I had extra time at the end of a speech, I would just start listing them off from the top.</p>
                        <p style={{padding : '1rem'}}>To maximize the effectiveness of your link TURN, you need a better warrant than your opponent for the link (i.e. a compelling reason why their original link was wrong).  This shouldn’t be a problem if you follow the research strategies outlined in the Research chapter.  Usually it sounds something like “my opponent’s contention failed to take into account X, therefore the link TURN happens.”</p>
                    </AccordionItem>
                    <AccordionItem title='Impact TURN'>
                        <p style={{padding : '1rem'}}>An impact TURN is when you say that your opponent’s impact, assumed to be good, is actually bad.  If your opponent says that X leads to Y and Y is favorable, an impact TURN would respond X leads to Y but Y is actually unfavorable.</p>
                        <p style={{padding : '1rem'}}><strong>Example: </strong>“My opponent’s second contention is that establishing a universal basic income, would lead to major inflation within the U.S.  However, TURN this against my opponent because inflation would be incredible beneficial right now, as it would help eradicate the large amount of federal debt.”</p>
                        <p style={{padding : '1rem'}}>I have the same problem with impact TURNS as I do with non-unique arguments.  You implicitly concede the link to the impact and you don’t know what other tricks your opponent can pull with that link.  It’s also more rare to find impact TURNS since usually impacts are things like racism and poverty which is obviously bad.  You cannot layer an impact TURN with a link TURN since it would just double TURN the argument, so if you have to choose generally always go with the link TURN.  It’s also faster to read link TURNS and you have more options to build off of the opponent’s next response that way.</p>
                    </AccordionItem>
                </Accordion>
                <h2>Layering</h2>
                <p>Layering your rebuttal is a great strategic technique that forces your opponent to win multiple layers of arguments in order to get access to their contention.  Argument layering is usually characterized by the “even if” statement as you generate new hypotheticals about their argument and continue to prove why every step of the way it’s still flawed.  It’s much harder for the opposition to group layered arguments together, as opposed to a stack of arguments which means its a big plus when it comes to time efficiency too.</p>
                <p><strong>Example: </strong>“My opponent claims that banning guns would lead to less crime.  This is false because a gun ban would lead to the creation of a black market increasing illegal gun sales. Even if this wasn’t the case, decreasing the number of guns would only affect law abiding citizens, and criminals would continue holding on to their firearms.”</p>
                <p>Note: You can layer as many arguments on top of each other as you want, but usually if your layer hits a depth of 3, your opponent just gives up the argument.</p>
                <h2>Collapsing</h2>    
                <p>A key difference between an experienced and inexperienced poker player, is that an experienced player only plays the best hands, while an inexperienced player often plays way more hands than he should.  Similarly, in a debate round, you aren’t going to be able to get through every single argument on both sides of the flow during your rebuttals.  A good debater knows how to collapse and when to collapse to their stronger arguments towards the end of the debate.  This will highlight to the judge which exact arguments are important so they won’t have to assess a million different points when they eventually make their decision.</p>
                <p>Before your next speech take a long look at your flow and start asking yourself these questions:</p>
                <Accordion>
                    <AccordionItem title='Where are the Prerequisites?'>
                        <p style={{padding : '1rem'}}>Which arguments are or can potentially become prerequisites to the others?<br/><br/><strong>Example: </strong>Providing better teachers for elementary school students can potentially be a prerequisite to educational improvement, crime rates, or racism (white flight).</p>
                    </AccordionItem>
                    <AccordionItem title='Where are the Conditional Arguments?'>
                        <p style={{padding : '1rem'}}>Is there an argument in this round, that, if proven true, will make multiple other arguments false?<br/><br></br><strong>Example: </strong>Proving that X policy boosts the economy potentially takes out arguments like homelessness, poverty, and crime rates.  At the very least it makes it much easier for you to make those arguments and for them to be believable.</p>
                    </AccordionItem>
                    <AccordionItem title='Where is the Weakest Argument?'>
                        <p style={{padding : '1rem'}}>Which argument does your opponent seem least comfortable dealing with, and has your judge been adequately receptive to that argument during the round?  If so, that’s a good hint that that’s the right argument to go for.  Conversely, if an argument has 5 responses on it that can’t be grouped, you should probably ditch it.<br/><br/><strong>Example: </strong>If your opponent clearly doesn’t know how to handle a contractarian framework, and your judge is experienced, push it through for the win.</p>
                    </AccordionItem>
                    <AccordionItem title="Where are the Root Links?">
                        <p style={{padding : '1rem'}}>Visualize all the links in your opponent’s case, and try to trace them back to a root link.  If you can’t find one, look for links that create the foundation for multiple other links: that link is the most important one to target.<br/><br/><strong>Example: </strong>You opponent has three arguments.  He says that a universal basic income will lead to higher taxes which deters green technology, that the middle class will have less money for housing and food, and decreased consumer confidence which leads to less investment in small companies.  All three of these arguments rely on a single link or assumption: that a universal basic income will result in increased taxes.  If you take out this link, and add a bit of your own analysis, all three arguments fall.  If your opponent is smart, the link chains won’t always be black and white, and it’s your job to see the invisible links and solidify them in your rebuttal.</p>
                    </AccordionItem>
                    <AccordionItem title='Where is the Biggest Impact?'>
                        <p style={{padding : '1rem'}}>What is the biggest Impact in the round?  Keep in mind the judge needs to be receptive to the impact as well.  Extinction arguments usually don’t fly over well with traditional judges, look for the next biggest impact that the judge buys.<br/><br/><strong>Example: </strong>The judge doesn’t buy that the U.S. starts a nuclear war with Russia, but will consider the possibility of a Cold War situation where both countries are on the brink of nuclear war.</p>
                    </AccordionItem>
                </Accordion>
                <p>The questions above that you ask yourself are all part of the process to discover which FEW arguments you will go for in your next speech (especially if it’s a short one like the 2AR).  And these connections aren’t always going to be immediately clear in the round.  It is your job to see where on the flow it is possible to create these arguments and then present them in your rebuttal speeches.<br/><br/><strong>Example: </strong>“Judge there have been many different arguments presented in today’s round.  However there are really only three key arguments that are truly important for they serve as the link to the most important impacts in today’s debate.”</p>
                <p><strong>Example: </strong>“Evaluate my contention 2 first as it is the most important argument and is functionally a prerequisite to every other argument presented in the debate”</p>
                <p>A big part of collapsing is weighing.  When you collapse, you are inherently going to concede some arguments, so to clean things up on the flow and make the narrative clear to your judge, you’re going to want to do some weighing between the arguments you go for vs. the arguments you don’t.  Make it clear why the argument’s you are going for are the most important arguments!</p>
                <p><strong>Note: </strong>A lot of time’s I’ve seen debaters use weighing argument as rebuttals during their rebuttal speech.  This just doesn’t seem very time efficient to me because you know you’re going to have to bring up weighing again in your final speech for consolidation purposes.  Why not keep the element of surprise and your time, and save it for the final speech?</p>
                <h2>Weighing</h2>
                <p>Weighing is just that: weighing two different arguments or impacts and explaining why one is more important and thus “outweighs” the other.  It is efficiently used when presented in the last speech to wrap up loose ends.</p>
                <p>There are few different factors to consider in weighing analysis.  One of these or multiple combined together can be presented as the justification for why X outweighs Y.</p>
                <Accordion atomic={false}>
                    <AccordionItem title='Magnitude'>
                        <p style={{padding: '1rem'}}>Magnitude, how big an impact is, is probably the most important weighing mechanism since it’s intuitive that if one impact has a greater magnitude of effect it should outweigh the impact of smaller magnitude.<br/><br/><strong>Example: </strong>“My contention 2 about environmental degradation outweighs my opponents points about economic decline, because a few people starving is bad, but nowhere near as bad as an entire ecosystem collapsing and causing a plethora of natural disasters which will kill thousands.”</p>
                    </AccordionItem>
                    <AccordionItem title='Probability'>
                        <p style={{padding: '1rem'}}>Probability is basically how likely an event is to occur.  Most of the time, neither debater is going to able to prove without a doubt that a consequence will occur, so this weighing mechanism states that the argument which has a higher probability of occurring should be more important.  Also fairly intuitive.<br/><br/><strong>Example: </strong>“My opponent’s arguments about nuclear war sound alarming, but have an extremely low chance of occurring given the principle of mutually assured destruction.  Prefer my impacts on food shortages since they actually have a high chance of occurring.”<br/><br/><strong>Note: </strong>Remember to have warrants for why your impact has a higher probability of occuring!<br/><br/><strong>Tip: </strong>You can also indirectly control the magnitude using probability by saying “the strength of the link determines the strength of impact.”  This is a solid principle based in Statistics.  A 50% chance that 100 people will die is going to worse than a 1% chance of 1,000 people dying.</p>
                    </AccordionItem>
                    <AccordionItem title='Cyclical'>
                        <p style={{padding: '1rem'}}>Cyclical impacts are those that continue occurring and over years aggregate into a much bigger impact.  If you know your opponent’s impact is of greater magnitude you can use the fact that your impact is cyclical to prove that you win in the long term.<br/><br/><strong>Example: </strong>“Racism outweighs a 2% drop in U.S. GDP.  The economy can recover but racism is structurally ingrained in society and thus the impact aggregates every year.  In 10 years, the economy will be just as strong but people will continue to be oppressed and killed in this vicious cycle until we take direct action to solve this problem.”<br/><br/><strong>Note: </strong>Cyclicality make arguments about racism and poverty really dangerous.  Impacts like racism and intergenerational poverty don’t kill millions a year, but without direct action, these issues will continue to be exacerbated, and over years can add up to something like hundreds of thousands of deaths.</p>
                    </AccordionItem>
                    <AccordionItem title='Timeframe'>
                        <p style={{padding: '1rem'}}>Timeframe defines how much time it takes for the impact to happen.  If the impact happens a long time from the present, you can say that an impact which happens very soon should outweigh because 1) We should solve the problem immediately in front of us (that’s how policymaking works) 2) There’s a good chance that new solutions will emerge in the future to combat the impact down the road, so there’s no rush right now 3) There’s a chance that the impact in the future won’t even happen or at least will change dramatically given the millions of policies and variables that will change from the status quo.<br/><br/><strong>Example: </strong>“Poverty outweighs the potential for overpopulation 50 years from now.  As policymakers we should solve the immediate problems in front of us first especially when there are thousands starving, before moving on to tackle overpopulation.  Furthermore, new policies and technologies will emerge in the future to give us a better idea of how to fix this issue, so let’s focus on the big problems happening now.”<br/><br/><strong>Note: </strong>Timeframe should never be the sole reason to outweigh.  It’s better to pair it with another factor like probability.</p>
                    </AccordionItem>
                    <AccordionItem title='Reversibility'>
                        <p style={{padding: '1rem'}}>Reversibility basically asks if the damages of the impact are reversible or not.  If the damages are irreversible then it is arguable much worse.  Debaters usually use the point that extinction is irreversible to try and beat back probability weighing analysis that says it’s unlikely.  Death is also irreversible.<br/><br/><strong>Example: </strong>“War outweighs economic collapse on reversibility.  People can always earn their money back but people dying during the conflict can never be undone.”</p>
                    </AccordionItem>
                </Accordion>
                <h2>Overviews</h2>
                <p>Your rebuttal speeches should generally always start with an overview (about 30 seconds) that summarizes why you are winning on a high level.  Maybe you choose to explain why a dropped argument was actually the most important argument in the round, or maybe you choose to highlight a key deficiency in your opponent’s case or evidence.  Either way, the overview will be most memorable to your judge so use it to point out the biggest issue and build off from there. </p>
                <p>If your opponent’s speech before was overly defensive, meaning most of their arguments were defensive in nature, point that out to the judge.  Maybe they conceded framework?  Explain the implications of what that means in terms of what arguments have been zoned out.  I know I know, isn’t this something I would normally advise to be saved for the last speech?  Overviews are the only exception, because you are literally picking the most important and most undercovered aspect of the debate -you might just win the round right then and there, so it’s an okay move in my book!</p>
                <p><strong>Examples: </strong>“Before we get into the nuances of each argument, I would like to point out that on a high level the majority of my opponent’s responses have been defensive in nature.  This means that for the most part, my opponent hasn’t upheld his burden of proving that the aff/neg position is bad but rather posited that the aff/neg position simply isn’t as amazing as it could be.  This isn’t a reason to vote for the other side, and I will clarify this more in my final speech.”</p>    
                <p><strong>Examples: </strong>“The vast majority of my opponents arguments deal with faults with the current system.  That isn’t what the aff/neg is advocating for.  Rather, we have multiple plans in place which learn from the errors of our past and none of these new changes have been addressed by either my opponent’s evidence or his rebuttals.”</p>
                <p><strong>Examples: </strong>“My opponent has dropped my third and final contention.  As you can see there is not a single response on it.  Unfortunately, this will soon become the most important argument this round, and he will not be allowed to respond to it anymore since it has been cold conceded.”</p>
                <p><strong>Examples: </strong>“My opponent has completely conceded my rights based framework, dropping the evidence by X who says Y.  This means none of my opponent’s contentions matter in the grand scheme of things since they do not protect the citizens’ negative rights.”</p>
                <p></p>
                <h1>Advanced Rebuttal Strategies</h1>
                <h2>The Time Efficiency Model</h2>
                <p>In chess, the centipawn is used to measure the points per the positional advantage you gain from each move.  If you were to only look at points with regard to the number of pieces you captured vs. the number of pieces you lost, you would actually have a very one dimensional and inaccurate view of the game.  Similarly, debate should be seen as more than just the arguments left standing or arguments taken out.</p>
                <img src='https://elevatemychess.com/wp-content/uploads/2017/09/Chess-PNG-Pic.png' alt='chess' width='50%' height='50%'/>
                <p>Given that we assume a certain quality level for each argument, It would be really helpful if there were a way to calculate the exact “strength” of each rebuttal like in chess.  A way to measure how much closer a particular argument pushes you to checkmate.  Assuming we can make quality responses to every argument posed by the opponent, how can we establish the hierarchy of these arguments so that the most optimal one’s are prioritized?</p>
                <p>In my experience, I have used time cost/gain to get a more accurate idea of an argument’s strength.  There is a finite amount of time given to each debater every round.  You can almost think of it like currency; once you’ve spent it all you’ve lost.  A time efficient argument is one that you know will cost your opponent more time responding to it, than it cost you to make it.  It means you’ve “won” time  for yourself and “stolen” time from your opponent.</p>
                <img src='http://www.rifemagazine.co.uk/wp-content/uploads/2016/11/Untitled-12.jpg' width='50%' height='50%' alt='time'/>
                <p>This seems like a simple enough concept but takes practice to master because there are a lot of moving pieces that you need to consider.  The are three main variables that you need to keep track of for each argument to make the calculation are: time you spend making the response, predicted time your opponent spends to answer, and the importance of the argument. </p>
                <p>Takeaways from these three rules: </p>
                <Accordion>
                    <AccordionItem title='1. Make Bad Responses if You Can Not Cover the Entire Flow'>
                        <p style={{padding: '1rem'}}>The first response you make to an opponent’s contention has the highest time efficiency.  They are incentivized to respond to it no matter how bad the argument.  So always have at least one response on each contention even if you have no idea what’s going on.  It’s almost always going to be a time winning move.</p>
                    </AccordionItem>
                    <AccordionItem title="2. Balance Responses">
                        <p style={{padding: '1rem'}}>Don’t overkill contentions.  After you read the 3rd or 4th response, the predicted time your opponent spends in his answer falls dramatically as he will likely give up on the contention and collapse to a different argument instead.  Every additional response you place after the 3rd actually loses you time statistically.  I know how cool it feels to have 10 responses on a contention but just know it’s not the optimal move.</p>
                    </AccordionItem>
                    <AccordionItem title='3. Do Not Make Bad Responses if You Can Cover the Entire Flow'>
                        <p style={{padding: '1rem'}}>If you are able to cover the entire opposing case, don’t read suboptimal rebuttals.  If anything, use the extra time to strengthen the existing ones.  If you cover the whole case with efficient responses but also read some with shaky logic, there’s a good chance your opponent answers all the efficient arguments and drops the bad ones.  Yeah, they’re still on the flow but all of that still counts as lost time and none of them were going to be the deciding factor anyways.<br/><br/><strong>Exception: </strong>If your opponent has proven in the round that he isn’t very debate smart you can read bad arguments as a time suck.  But they should be read at the top before your good arguments.  Most debaters feel compelled to answer the first two responses on their case first since they assume they’re the most important.</p>
                    </AccordionItem>
                    <AccordionItem title='4. The More Important the Argument the More Efficient'>
                        <p style={{padding: '1rem'}}>Remember how we talked above about how to determine the most important arguments in the round?  Having responses on those arguments are the most time efficient because not only does it indirectly attack other arguments on the flow, when you eventually collapse to it, if done strategically, all the responses your opponent has on everything else becomes time lost.  This also means don’t overcommit to arguments you know won’t be collapsed to because that’s just time going down the drain after the collapse.</p>
                    </AccordionItem>
                    <AccordionItem title='5. Response Ordering'>
                        <p style={{padding: '1rem'}}>Since debaters tend to respond to arguments top down for organizational purposes the first response on a contention should be the biggest time suck, followed by another time drain, and then your offense.  If your arguments were all efficient, your opponent won’t have time to go through the TURNS.  I usually read four responses to each contention.  First two are usually defensive (non unique, or no warrants), and the last two are link TURNS.<br/><br/><strong>Discussion: </strong>For those of you asking “isn’t it more time efficient to read 4 TURNS?”  Well, it’s close but I think my combination is slightly better because it’s easier to layer defensive arguments with offensive arguments which makes it harder to group the responses together.  It also takes less time to make defensive arguments since you don’t have to read evidence, and more time to respond to because you use strategic wording like “burden of proof” to pressure the opponent.  If you have 4 TURNS that are unique enough that they can’t be grouped and logical enough that you don’t need to read lots of evidence go for it, but that usually won’t be the case.</p>
                    </AccordionItem>
                </Accordion>
                <p><strong>Conclusion: </strong>Your goal during the rebuttal is to come up with quality arguments against each contention, THEN sort those arguments by time efficiency.  </p>
                <h2>Making Time Efficient Rebuttals</h2>
                <p>To determine if your rebuttal is time efficient you can try asking yourself these questions: </p>
                <Accordion>
                    <AccordionItem title='Does it Build Logic off Evidence Already Present in the Round?'>
                        <p style={{padding: '1rem'}}>A rebuttal that builds off your opponent’s existing argument will take less time to read while still being compelling.  Building off an existing arguments means you need to specifically use the already present logic within that argument to explain why it’s wrong.  This will almost always be a time winning move because if your opponent wants to answer, he needs to deconstruct or clarify his own logic first, then explain why your logic is wrong.  You will usually get at least a 1.25 time return on these arguments.<br/><br/><strong>Example: </strong>“My opponent claims that welfare causes dependency on the government.  That logic is backwards  because we literally created the government so that we could depend on them for survival.”<br/><br/>A rebuttal that builds off your own existing argument is called a “cross application” and will be more persuasive but also more dangerous because you create a new link between the contention and rebuttal (this means taking out one could potentially take out the other).</p>
                    </AccordionItem>
                    <AccordionItem title='Is it Intuitive?'>
                        <p style={{padding: '1rem'}}>If your rebuttal is intuitive it will almost always be a time winning move.  Even if the non-intuitive answer is the correct one, your opponent will have to spend more time justifying the non-intuitive argument.  <br/><br/><strong>Example: </strong><br/><br/>You: “A carbon tax on oil companies simply means they will pass the cost to consumers by raising the price of oil to offset the cost”<br/><br/>Your opponent: “A carbon tax won’t actually be passed off to the consumer.  The market for oil is still very competitive which means no single company can afford to skyrocket prices.  Because of this competition it is more likely that the companies will bite into their profits a little bit and just raise the price of oil a little bit.  This won’t really affect consumers, and even if it does it’s worth it to help the environment.”<br/><br/>Even though your opponent is probably correct it’s so much harder to explain to a layman and the time cost is ridiculous.  If responding to every argument takes you twice as long as your opponent you’re going to lose the debate.<br/><br/><strong>Example: </strong>If your opponent says the right to housing to part of the right to life you can say, “Well the right to a personal health trainer is also part of the right to life under your logic, but the government doesn’t give everyone a personal health trainer.”<br/><br/><strong>Conclusion: </strong>The simpler and more intuitive the argument the better.</p>
                    </AccordionItem>
                    <AccordionItem title="Does it have ONE warrant?">
                        <p style={{padding: '1rem'}}>Does your rebuttal have exactly one warrant that makes it persuasive?  On top of that, is it the shortest warrant out of all the possible warrants you can choose?  Each rebuttal should have one warrant but no more than that.  You don’t want to start over explaining things until after the collapse.  Think about it, if your opponent respond to your rebuttal, you can always read new warrants in the next speech, but if he doesn’t, all the extra warrants you read would be time lost.  To avoid a potentially time losing move, your rebuttals should be limited to one warrant each.  Remember, don’t overcommit until after the collapse and you know which arguments are actually important and which aren’t.<br/><br/><strong>Example: </strong>“The right to housing wouldn’t actually solve homelessness because there is a shortage of houses in the regions where homelessness is highest.”<br/><br/>Obviously there are many more reasons we might think of for why a right to housing wouldn’t fix homelessness, but for now, we provide this one warrant, and save the others depending on how the opponent reacts.</p>
                    </AccordionItem>
                </Accordion>
                <p></p>
                <h2>Word Economy</h2>
                <p>Getting good at word economy really just takes practice.  You have to keep asking yourself if there’s a clearer simpler way to explain what you just said and iterate.  In general you want to keep your early rebuttals as bare bones as possible: just a claim and warrant.  Once the response is over a sentence you should start questioning whether the words are being used as efficiently as possible.  Remember, keep your explanations simple in the first speeches then elaborate later depending on how your opponent reacts.</p>
                <h2>Grouping Arguments</h2>
                <p>Grouping arguments are great time winning moves, and absolutely necessary when you collapse.  The tricky part about grouping your opponents arguments is finding which arguments can be grouped in the first place.  To do this, you want to look at each argument and search for where their links converge as you trace them backwards.  Once you’ve found the component or evidence necessary for all the arguments to work, take it out.</p>
                <p><strong>Example: </strong>“Arguments 1, 2, and 3 all rely on the assumption that X is true.  Let me explain why X is false.”</p>
                <p>Sometimes, arguments don’t share the same parent link, but they do share similarities across the board that make them an easy target for grouping. </p>
                <p><strong>Example: </strong>one way to group arguments is to say, “these three arguments are all defensive in nature and don’t actually provide a reason to vote against me.”  Remember of course that this type of analysis belongs in your last speech, or else you would have to repeat yourself twice and it would be a time losing move.  </p>
                <p><strong>Example: </strong>“These three pieces of evidence were all written by unprofessional biased authors which calls into question their legitimacy.” </p>
                <p>When you collapse you use a slightly different form of grouping.  You want to take all the arguments you won’t collapse to (or at least a large chunk of it) and explain why they are all less important or dependent on the arguments you will collapse to.</p>
                <h2>Grouping Evidence</h2>
                <p>Grouping evidence is a rare type of evidence that attacks a large body of literature.  In doing so, it has the ability to group and attack multiple pieces of evidence at once. </p>
                <p><strong>Example: </strong>“According to Professor Ming from Stanford, almost all studies on global warming draw data from the World Health Organization which overestimates many variables in their model leading to high inaccuracies.”</p>
                <p><strong>Example: </strong>“According to an NHA report, the majority of studies on housing are flawed since they only track participants for a few months, whereas the biggest trends are only seen after 2 years.”</p>
                <p>As you can see in the examples above, one piece of evidence has the potential to take out every piece of evidence your opponent reads on a specific topic.  That’s a big time winning move.  When you prepare evidence for your rebuttal speeches, incorporate these types of articles.</p>
                <h2>Scoring the Flow</h2>
                <p>Something that we can’t forget to incorporate into our model of debate is the judges.  I’ve seen a lot of debaters get so wrapped up with how the arguments are interacting with each other that they forget how the arguments are interacting with the judge.  Before, we focused on measuring time efficiency to determine the “strength” of arguments.  Now let’s also consider “strength” with regard to how much the arguments resonate with the judge.  Doing so lets us control the ethos for each debater to a larger degree as well.</p>
                <p>Towards my last year of debate, I started to add scores on my flow to represent how strongly the judge bought each argument (scale 1-4).  Whenever you’re flowing, always be studying your judge’s expressions.  Which arguments confuse them?  Which arguments do they find personally offensive?  Which arguments do they personally resonate with?  Which arguments are they even writing down on the paper? Then, mirror that.  During CX and rebuttal speeches when you are responding to your opponent’s case, be angry at the arguments that offended the judge, be confused at the arguments that confused the judge, and pull out every single attack against the arguments that the judge seemed to agree with.  In doing so, you also establish rapport with your judge without being obvious, and this can sometimes be the difference in close rounds.  </p>
                <p>Your response depending on the score:</p>
                <Accordion>
                    <AccordionItem title='1'>
                        <p style={{padding: '1rem'}}>Scoring a 1 on an argument means that the judge absolutely did not buy it.  It means when the argument was read, the judge might have rolled his or her eyes, frowned in anger or disbelief, or just didn’t write the argument down.  This now factors into time efficiency.  It won’t matter how time efficient your rebuttals are, putting more than one response on an already dead contention is a time loss move.</p>
                    </AccordionItem>
                    <AccordionItem title='2'>
                        <p style={{padding: '1rem'}}>Scoring a 2 on the an argument means the judge was confused about it.  He clearly didn’t write much down and seemed to be consistently tilting or shaking his head.  Now how do we case these types of arguments into the abyss as efficiently as possible?  We can’t respond with sound logic right, because the judge doesn’t even understand what the argument was to begin with.  We don’t want to clarify the argument for the judge either since that’s just helping the opponents and having to clarify an argument before responding to it is a time loss move.  </p>
                        <p style={{padding: '1rem'}}>What you want to do is make the argument even more confusing and push it over the edge.  Give one rebuttal that is just as vague and confusing as the contention itself, and now, in the judges mind, that contention has been so totally warped, he’s given up on it.  That’s the fastest way to cast a 2 into oblivion.</p>
                        <p style={{padding: '1rem'}}><strong>Example: </strong>In a prelim round at a National Circuit PF tournament, I remember my opponents read an argument about satellite detection technology and clearly had no idea what the evidence was saying.  The judge was just as confused so in the next speech, I went up and talked about how satellite imaging was overlaid on top of GIS systems which were faulty.  What exactly are GIS systems?  Nobody in that round knew.  But now that a contention had two connected components that the judge had no idea about meant there was no way he was voting off it.</p>
                    </AccordionItem>
                    <AccordionItem title='3'>
                        <p style={{padding: '1rem'}}>Scoring a 3 means the argument is pretty believable and there no stand out reactions that the judge gave away.  This means just deal with it normally.  There’s no need to factor in judge considerations just go with the standard time efficiency model for rebuttals.</p>
                    </AccordionItem>
                    <AccordionItem title='4'>
                        <p style={{padding: '1rem'}}>Scoring a 4 means the judge really bought the argument.  He or she either nodded profusely throughout the speech or wrote down large amounts of text.  Dealing with 4s are tough.  You might have to forego time efficiency and really overcommit on these arguments.  This is one of those times you might have 5 or 6 responses on a contention with long explanations.  But, if you are being time efficient on all the other arguments, you should have enough time.</p>
                    </AccordionItem>
                </Accordion>
                <h2>Destroying the Presentation of The Argument</h2>
                <p>This goes all the way back to Aristotle’s three proofs: Ethos, Logos, Pathos.  We’ve gone over pretty in depth how to take out the logos of an argument, but how do you attack the other two frameworks for persuasion?  The way you attack ethos and pathos is to attack the very presentation of that argument: to say that the very idea of the argument is based in immorality.  This takes away credibility from the other side, and establishes your own moral high ground.</p>
                <p><strong>Example: </strong>“Not only is it untrue that welfare makes the poor more lazy, the argument is based in historically oppressive assumptions that stereotypically paint all poor people as parasites.”</p>
                <p><strong>Example: </strong>“Saying you have nothing to fear if you have nothing to hide is an extremely problematic idea based in historically racist policies like NYC stop and frisk.  It would mean people like the judge and I have no rights and could be invasively searched without our consent at any time.</p>
                <p>Notice how the above examples destroy the very idea behind the argument.  It paints the opposing side as the moral evil to strengthen the perception of your own moral compass.</p>
                <h2>Independent Voters</h2>
                <p>Independent voters are arguments you define to be so important that, if won, they are an independent reason to vote for you (irrespective of everything else that takes place in the round).  Of course, you also need to provide a good reason for why the argument is an independent voter too (now it just sounds like weighing right).  It usually happens when your opponent makes a major error.  If you catch your opponent cheating, or reading abusive arguments there could be cause for an independent voter.</p>
                <p>When you say that one of your own arguments is an independent voter, you generally want to save it for the last speech because you don’t want to risk your opponent reading a TURN against it in the next speech.  There are a few exceptions to this, like when your opponent drops a framework or definition argument that can’t be TURNed, where you should bring it up as soon as possible though.</p>
                <p><strong>Example: </strong>“My opponent has conceded my definition X.  This means none of his arguments apply anymore since they all talk about Y.  This is an independent reason to vote for me since my opponent’s entire case is not topical.”</p>
                <p><strong>Example: </strong>Topic -A just government ought to prioritize civil liberty over security.<br/>“My opponent has conceded my framework that for a state to be legitimate it must first ensure protection of the people.  This is an independent reason to vote for the neg because any country that doesn’t prioritize security is not definitionally “just.”</p>
                <p>When you say that one of your opponent’s arguments is an independent voter you are usually saying that one of their arguments is so problematic that they should lose for it immediately.</p>
                <p><strong>Example: </strong>“My opponent advocates a policy that justifies racism and slavery.  This is an extremely problematic argument that should be an independent reason to vote against my opponent because of the violence it recreates in the real world.  We can also probably agree that no case that justifies slavery could ever be morally correct.”</p>
                <h2>Should I Read it as a TURN or Contention?</h2>
                <p>As the negative, a lot of times you stumble across an argument but can’t decide whether to read it as part of the case or as a TURN on the aff.  Most of the time, it can be read as both, but if we’re being organizationally solid you should generally follow this formula.</p>
                <ol>First of all, it’s always more advantageous to read an argument as a TURN than as a contention given that all the argument’s components remain the same because...
                    <li>Reading an argument as a TURN is a reactionary strategy.  This means you have more options and can either choose to read it or not depending on what the opponent does.  Maybe the way the aff case is structured makes you decide to save the TURN for a later speech. </li>
                    <li>TURNS build off an argument that your opponent has already started.  This means you spend less time reading an argument that provides the same return value.  Very time efficient.</li>
                    <li>Your opponent taking out a TURN is seen as less dominant than them taking out a contention level argument.</li>
                </ol>
                <p>Okay well then why don’t we just only read TURNS as the neg?  Remember, you still need to read framework (good time efficiency) and that means you need contentions under that framework to make it make it a credible threat.  Furthermore, many traditional judges believe that the neg should have its own unique case position and will vote against you based on the idea that you don’t have a case to defend.</p>
                <p>So, an argument should be read as an individual contention if it contains multiple links (which means it takes a while to explain), has its own unique definitions (any time you have to define or explain a component of the argument it should probably be read as a contention), or specifically links to your framework (it’s a no brainer if that’s its strategic purpose).</p>
                <h2>Double Bind</h2>
                <img src='https://images-na.ssl-images-amazon.com/images/I/31MQ-Qiw99L._SX425_.jpg' width='30%'/>
                <p>A double bind is a type of rebuttal where you claim that whether or not your opponent’s argument is true, he loses either way.  It usually uses the either-or phrasing and can demolish arguments really effectively.  Here is the general form of the argument.  “My opponent’s contention 1 is under a double bind.  Either X happens which leads to Y which is bad or X doesn’t happen which means Z happens which is just as bad.”  A double bind can also be applied to the debate as a whole.</p>
                <p><strong>Example: </strong>“My opponent is in a double bind.  Either a UBI is passed through a Republican House which means the bill will contain provisions to phase out welfare, cutting life support from the bottom 10%, or the bill doesn’t pass at all which means none of my opponent’s impacts actually happen.”</p>
                <p>A double bind can also be used to prove the falsity of an argument.  You can put a double bind on the internal logic of an argument.  “My opponent believes that if X happens Z will definitely happen.  This is false there is a double bind on his logic.  If you buy my opponent’s base assumption that X happens this means either Y or M would happen which makes Z impossible.</p>
                <p><strong>Example: </strong>The premise is that your opponent says standardized testing leads to better child brain development as shown in higher test scores.  You say, “Standardized testing at an early age can’t possibly be good for child brain development.  This is a double bind.  EITHER you agree with my evidence that testing requires decrease in play time which means sacrificing cognitive development OR testing trades off with other classes such as science and art, which leads to less development in the frontal lobe, and as a result dulls creativity.”</p>
                <h2>Dropping Arguments Strategically</h2>
                <img src='http://debate.potentspeaking.com/wp-content/uploads/2015/01/Argument-drop.png' height='30%' width='30%'/>
                <p>We talked about in the collapsing section how some rounds you will inevitably have to drop arguments to pursue the more important ones.  One thing you don’t want to do is just ignore it and pretend it doesn't exist -that actually makes it stick out like a sore thumb to both your opponent and judge.  You also don’t want to just ouweight it -it looks like you're lowkey attacking your own argument and some judges won’t see a direct connection between the arguments.  </p>
                <p>To make that direct connection clear to all parties involved, you should weave the dropped argument into the narrative of your round, and more precisely into the narrative of the winning argument you decided to collapse to.  Make the dropped argument a component of the winning argument but make it clear that one is inferior to the other.</p>
                <p><strong>Example: </strong>“My opponent has a lot of rebuttals against my point about education.  Although some might be true, education is only one small component of the biggest issue of this round: poverty.  Even if it isn’t extremely clear how much education is improved by, the fact that we are able to provide food and shelter, prevent people from starving, and reduce mass incarceration, means we hold the biggest link to lifting people out of poverty.”</p>
                <p>A lot of debaters, in the above example, would simply ignore the contention about education if it was beaten, or worse, waste an enormous amount of time trying to revive the dead.  By incorporating education into the grand narrative about solving poverty, you acknowledge that you haven’t lost the point on education but rather see it as more of an inferior component of the round’s biggest issue.  So much better.</p>






            </main> 
        )
    }
}

export default Rebuttals;