import React from 'react';
import './SpeechesLD.css';

class SpeechesLD extends React.Component {
    render() {
        return (
            <main className='body'>
                <h1>Speeches</h1>
                <h2>Affirmative Constructive (1AC) : 6 minutes</h2>
                <p>This is the first speech by the affirmative where you basically just read the case you prepared.  In terms of strategy, there’s not much to say here.</p>
                <h2>Cross Examination : 3 minutes</h2>
                <p>Here the neg get’s 3 minutes to ask the aff questions about their case and clarify/attack points.  We talk a lot about strategy here in the “CX” tab, but mainly your goal is to make sure there are no sketch framework tricks and make sure your opponent look stupid.</p>
                <h2>Neg Takes Prep : 2/4 minutes</h2>
                <p>This is a very strategic place for the neg to take prep.  The aff doesn’t know the neg position yet, so they have nothing to prepare for during this time.  You don’t need to take the full 2 minutes just as much as you need to come up with adequate responses to the aff case.  Three against each contention is the average but there are some exceptions with weirder unorthodox cases.  Furthermore, ask for specific pieces of evidence during this time -verify that some of the more ludicrous arguments are actually true.</p>
                <h2>Negative Constructive (1NC) : 7 minutes</h2>
                <p>Here, the neg is given 7 minutes to both read it’s own case and also respond to the affirmative case.  This is half a constructive speech and half a rebuttal speech.  Usually you want to spend no more than 3 minutes on your own case, and spend the last 4 minutes responding to the 6 minute aff constructive.  You have a good amount of time so you want to really swamp the aff case with (good) responses in this speech making the 1AR as tough as possible.</p>
                <h2>Cross-Examination : 3 minutes</h2>
                <p>Now the aff gets to ask the neg questions for 3 minutes.  Same deal.</p>
                <h2>Aff Takes Prep: 2/4 minutes</h2>
                <p>Aff should take a bit of prep here.  The next speech is very important so get a good idea of how you want this round to evolve.  Also, ask the neg for evidence for their most important arguments -verify they are true.</p>
                <h2>First Aff Rebuttal (1AR) : 4 minutes</h2>
                <p>The aff gets 4 minutes to answer the responses against the aff case AND respond to the neg case.  This is usually the hardest speech in the round because you have 4 minutes to respond to a 7 minute speech.  As the affirmative you want to start thinking about the end game and decide which arguments you will collapse to in the final speech.  Definitely don’t get caught up in the nitty gritty.  If you’re against a good opponent, you won’t be able to cover everything on the flow.  Answer the arguments that absolutely must be answered, then map out a winning scenario that you can push through in the last speech!</p>
                <p>A lot of debaters like to start collapsing in the 1AR so that they can feel like they’re covering everything on the flow.  Not sure that’s the best strategy.  You don’t want to reveal your entire hand yet, the neg still has a 6 minute speech.  I think what you want to do, is start emphasizing certain arguments to set them up well for a good collapse but don’t outright collapse immediately.  That way, your opponent still has to cover everything on the flow because he isn’t exactly sure what you might go for in the last speech and fear/anxiety is a very real feeling in the 1NR.  You don’t want to collapse in the 1AR, then have your opponent spend all 6 minutes on the arguments you collapsed to, unless you know for a certainty your opponent doesn’t know how to handle those arguments.</p>
                <h2>Neg Takes Prep : 4/4</h2>
                <p>Neg should take the rest of its prep here because it’s about to be the last speech.  Plan out your voters and preempt how you think the aff will collapse.  The only exception to this rule, when you shouldn’t use the rest of your prep, is when 1) you haven’t used prep all round and want to look like a boss and just impromptu the last speech (idk some judges are lowkey impressed by that) 2) you already mapped out the final speech while your opponent was talking and don’t need more time (and don’t want to give your opponent time to prepare as well).</p>
                <h2>Negative Rebuttal (1NR) : 6 minutes</h2>
                <p>The 1NR is very much a reactionary speech to whatever your opponent does in the 1AR.  Use 4.5 minutes as rebuttal time to cover both ends of the flow (the aff and neg case), then collapse, weigh, and bring up your voters in the last 1.5 minutes.  For those who don’t know, voters are usually the 2-3 most important arguments you bring up in the final speech and label as “key voting issues” for the judge.  This means those arguments should be the predominant one’s the judge uses to evaluate the round.</p>
                <p>During your voters, you should try and predict what arguments your opponent will go for and preempt them.  It’s not that you’re comparing your voters with your opponent’s, you are predicting how your opponent will respond to your voter, and answering accordingly.</p>
                <p><strong>Example: </strong>“The final voting issue is the economy.  A UBI would decimate the U.S. economy through increased taxation which is a net negative on consumer spending even after factoring in the effects of a UBI.  This is explained in my X evidence which was clearly dropped all throughout the round.  And my opponent will probably get up in the next speech and talk about how a UBI has the potential to save thousands of lives which is more important, but remember, my Y evidence explains that the economic recession caused by a UBI policy would actually offset any of those lives saved as millions starve for the next 10 years.  Even if my opponent claims it’s the “moral” thing to do, we have already agreed since the beginning that this round would be judged purely off who can actualize the best real world scenario.  If none of the benefits my opponents claims can happen actually take place, it’s clear that we have to negate.”</p>
                <p>I know I’ve generally been fairly critical of preempt arguments since it’s not a sure thing your opponent will bite into.  However, in your last speech, if your opponent is cornered, you can use preempts to literally close off their last route of escape.  A preempt is efficient, if you know that the opponent must either bite into it or just lose the round and you will have a very good idea of these scenarios by your last speech.  In the above example, we know for a fact that the opponent has lost the econ argument, his only out now is to try and outweigh with “lives saved” or “the idea is moral even if it’s not possible”.  Once you close off those last two routes it’s over.</p>
                <h2>Aff Takes Prep : 4/4 minutes</h2>
                <p>Aff should take the rest of its prep here -it’s the final speech and you need all the preparation you can get.  Decide which arguments you will collapse to, write out your weighing analysis, and if you have extra time craft a nice little inspiring call to action in the end.</p>
                <h2>Second Affirmative Rebuttal (2AR) : 3 minutes</h2>
                <p>Spend 1 - 1.5 minutes on rebuttal - respond to the arguments that matter most.  In the last 1.5 minutes collapse, list your voters, and do weighing analysis.  The 2AR is partly a reactionary speech to the 1NR, but not wholly so.  You should mainly stick to the plan you mapped out in the 1AR, don’t get caught up in some little detail the opponent brings up in the 1NR unless it can literally determine the round.  The 1NR is 6 minutes and your 2AR is 3.  Don’t get distracted by everything the neg says, you won’t be able to respond to it all.  Trust the plan.  Explain why everything else is less important rather than why it’s all wrong.</p>
            </main>
        )
    }
}

export default SpeechesLD;